spring.application.name=formgenerator
  
spring.datasource.url=jdbc:postgresql://localhost:5432/spark_digital_db
spring.datasource.username=postgres
spring.datasource.password=admin  
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.security.user.name=admin
spring.security.user.password=admin

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

aws.s3.endpoint=http://localhost:9000
aws.s3.accessKey=admin
aws.s3.secretKey=password
aws.s3.region=af-south-1
aws.s3.bucketName=my-bucket

